version: 2

defaults: &defaults
  docker:
    - image: circleci/ruby:2.4

workflows:
  version: 2
  validate-then-generate-docs:
    jobs:
      - validate_atomics_generate_docs

jobs:
  validate_atomics_generate_docs:
    <<: *defaults
    steps:
      - checkout
      - add_ssh_keys

      - run:
          name: Validate the format of atomic tests against the spec
          command: |
            bin/validate-atomics.rb

      - run:
          name: Generate nice markdown document for atomics
          command: |
            bin/generate-atomic-docs.rb
            git status

            git config credential.helper 'cache --timeout=120'
            git config user.email "<email>"
            git config user.name "CircleCI doc generator"
            
            git add atomics
            git commit --allow-empty -am "Generate docs from job=$CIRCLE_JOB branch=$CIRCLE_BRANCH"
            git log -n 3
            git status

            if [ "$CIRCLE_BRANCH" = "master" ]; then
              git push
            fi
